In [1]:
import sys
import numpy as np

Numpy is a backend for almost every scientific computing library. 
Why do we use Numpy?
* It gets translated to low level languages like C++ at runtime.
* Provides better runtime speed and memory optimization.
* Can be useful in processing huge data.

In [2]:
#Unlike Python, numpy only as much memory as required.
arr_a = np.array([9,8,7,6,5,4])
arr_a.dtype

dtype('int32')

In [3]:
arr_b = np.array([0,8.6,7.,6,5,4.4])
arr_b.dtype

dtype('float64')

But Python allocates 256 Bytes for all the variables which can become memory consuming in scietific computing.

In [4]:
arr_a[0], arr_b[1]

(9, 8.6)

In [5]:
arr_a[1:]

array([8, 7, 6, 5, 4])

We can also specify bits of memory if required.

In [6]:
arr_c = np.array([9,8,7,6,5,4], dtype = np.int8)

## Calculations

In [7]:
matrix_a = np.array([
    [1,2],
    [3,4]
])

In [8]:
matrix_a.shape

(2, 2)

In [9]:
#Number of elements in the matrix
matrix_a.size

4

In [10]:
matrix_b = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [11]:
matrix_b.shape

(2, 2, 3)

In [12]:
#But we should be careful while allocating elements in a matrix, if shape doesnt match it can give eronius results.
matrix_c = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9]
    ]
])

In [13]:
matrix_c.shape

(2,)

In [14]:
matrix_b[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [15]:
matrix_b[1][0]

array([7, 8, 9])

In [16]:
matrix_b[1][0][2]

9

In [17]:
#Also,
matrix_b[1,0,2]

9

In [18]:
matrix_a.sum()

10

In [19]:
matrix_a.mean()

2.5

## Broadcasting and Vectorized Operations

In [20]:
a = np.arange(4)

#### Please note, its arange not arrange. Its sort of 'a range'

In [21]:
a

array([0, 1, 2, 3])

In [22]:
a + 10

array([10, 11, 12, 13])

In [23]:
a

array([0, 1, 2, 3])

So, numpy creates an immutable array, 
the original array doesn't gets changed in-place but rather such operations create a new array

In [24]:
a = [1,2,3,4]
b = [5,6,7,8]

In [25]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
np_a = np.array([1,2,3,4])
np_b = np.array([5,6,7,8])

In [27]:
np_a + np_b

array([ 6,  8, 10, 12])

You can notice the difference between a normal python operation and numpy operation.
<br>Remember to add or subtract between two or more numpy arrays, they must be of same shape.

## Booleans

In [28]:
x = np.arange(4)

In [29]:
#Selecting index '0' and index '-1' from Numpy Array 'x'
x[[0,-1]]

array([0, 3])

In [30]:
x[[True,False,False,True]]

array([0, 3])

##### Did you notice any similarity in above two cells?

In [31]:
#Filtering
x >= 2

array([False, False,  True,  True])

In [32]:
x[x >= 2]

array([2, 3])

In [33]:
#it was basically saying
x[[False, False, True, True]]

array([2, 3])

In [34]:
x[x>x.mean()]

array([2, 3])

In [35]:
x[(x==0)|(x==1)]

array([0, 1])

## Linear Algaebra

In [36]:
matrix_x = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [37]:
matrix_y = np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [17,18,19],
        [70,71,72]
    ]
])

In [38]:
matrix_x + matrix_y

array([[[11, 22, 33],
        [44, 55, 66]],

       [[24, 26, 28],
        [80, 82, 84]]])

In [39]:
matrix_i = np.array([
    [1,2,3],
    [4,5,6]
])
matrix_i.shape

(2, 3)

In [40]:
matrix_j = np.array([
    [1,2],
    [3,4],
    [5,6]
])
matrix_j.shape

(3, 2)

In [41]:
#Remember we need two matrix with ixj and jxk shape to undergo dot product
matrix_i.dot(matrix_j)

array([[22, 28],
       [49, 64]])

## Numpy methods

In [42]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [43]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.arange(0,64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [45]:
A = np.arange(1,5).reshape(2,2)

In [46]:
np.ones_like(A)

array([[1, 1],
       [1, 1]])

In [47]:
np.ones([2,2]) * 10

array([[10., 10.],
       [10., 10.]])

In [48]:
np.ones([2,2],dtype = np.int8) * 10

array([[10, 10],
       [10, 10]], dtype=int8)

In [49]:
np.random.rand(2,2)

array([[0.58088761, 0.99113023],
       [0.98063619, 0.26976065]])

In [50]:
np.random.randint(2,6, size = 10)

array([4, 5, 4, 3, 5, 5, 3, 4, 4, 5])

In [51]:
np.random.randint(2,6, size = (2,2))

array([[5, 2],
       [5, 2]])